### PR TITLE
Make no player mode more attractive

### PR DESCRIPTION
**Pull request by pvtri96**

### CODE REVIEW

**Comment by NguyenTatNhac** [comment]
Please resolve conflicts!

**Comment by hynguyen2610** [comment]
Hi all, please confirm that:
- It's needed
- It's similar to old version

Nice day :)+

**Comment by NguyenTatNhac** [comment]
@hynguyen2610 it is new feature.
* In the old version, when user disable the player, then the player's place will be empty.
* With the changes come with this PR, when player is disabled, it will be a message on screen: "The player is disabled. Press <i className="fa fa-music" /> to re-enable the player."

**Comment by pvtri96** [comment]
I have resolved the conflicts

**Comment by pvtri96** [comment]
@hynguyen2610 this PR is not related to the old version but it is needed for UI/UX

**Pull request merged**
